/**
 * List of languages to exclude from log.
 */
const nonOutputLanguageIds = [
    //
    'plaintext',
    'bat',
    'clojure',
    'coffeescript',
    'jsonc',
    'c',
    'cpp',
    'csharp',
    'css',
    'dockerfile',
    'ignore',
    'fsharp',
    'git-commit',
    'git-rebase',
    'diff',
    'go',
    'groovy',
    'handlebars',
    'hlsl',
    'html',
    'ini',
    'properties',
    'java',
    'javascriptreact',
    'javascript',
    'jsx-tags',
    'json',
    'less',
    'lua',
    'makefile',
    'markdown',
    'objective-c',
    'objective-cpp',
    'perl',
    'perl6',
    'php',
    'powershell',
    'jade',
    'python',
    'r',
    'razor',
    'ruby',
    'rust',
    'scss',
    'shaderlab',
    'shellscript',
    'sql',
    'swift',
    'typescript',
    'typescriptreact',
    'vb',
    'xml',
    'xsl',
    'yaml',
    'sas',
    'm3u',
    'pascal',
    'vbs',
    'ACUCOBOL',
    'COBOL',
    'OpenCOBOL',
    'JCL',
    'dir',
    'pli',
    'source.css.jsx.styled',
    'gitignore',
    'autoit',
    'pgsql',
    'innosetup',
    'innopascal',
    'reg',
    'csv',
    'tsv',
    'csv (pipe)',
    'csv (tilda)',
    'csv (caret)',
    'csv (colon)',
    'csv (double quote)',
    'csv (equals)',
    'csv (dot)',
    'csv (hyphen)',
    'csv (semicolon)',
    'pip-requirements',
    'toml',
    'jinja',
    'jupyter',
    'aspnetcorerazor',
    'ahk',
    'vba',
    'cython',
    'msbuild',
] as string[];

export default nonOutputLanguageIds;
